name: Build Telegram iOS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'master'
      api_id:
        description: 'Telegram API ID'
        required: true
      api_hash:
        description: 'Telegram API Hash'
        required: true
      configuration:
        description: 'Build configuration'
        required: true
        default: 'Release'
        type: choice
        options:
          - Debug
          - Release

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: TelegramMessenger/Telegram-iOS
          ref: ${{ github.event.inputs.branch }}
          submodules: recursive

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.x'

      - name: Install dependencies
        run: |
          brew install cmake ninja buck python@3.11
          pip3 install buildconfig

      - name: Set up API credentials
        run: |
          # Create build configuration directory
          mkdir -p build-input/telegram-ios
          
          # Create API credentials file
          cat > build-input/telegram-ios/api-keys.json << EOF
          {
            "api_id": "${{ github.event.inputs.api_id }}",
            "api_hash": "${{ github.event.inputs.api_hash }}"
          }
          EOF

      - name: Run buck build
        run: |
          # Create a directory for build artifacts
          mkdir -p build/outputs
          
          # Generate project configurations
          python3 build-system/Make/Make.py \
            --generateProjectResources \
            --configurationPath="build-input/telegram-ios/api-keys.json" \
            --disableNetworkCapabilities

      - name: Build Telegram (No Code Signing)
        run: |
          # Build the app using buck
          buck build //Telegram:AppPackage#no-debug \
            --config custom.teamid= \
            --config custom.buildNumber=1 \
            --config custom.appVersion=1.0 \
            --config=custom.entitlementsPath=build-system/fake-empty-entitlements.plist

      - name: Create unsigned IPA
        run: |
          # Path to the buck output
          APP_PATH=$(find buck-out -name "Telegram.app" -type d | head -n 1)
          
          if [ -z "$APP_PATH" ]; then
            echo "Failed to find Telegram.app"
            exit 1
          fi
          
          echo "Found app at: $APP_PATH"
          
          # Create Payload directory and copy the app
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          
          # Create the IPA
          zip -r Telegram-unsigned.ipa Payload
          
          # Move the IPA to outputs
          mv Telegram-unsigned.ipa build/outputs/

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v3
        with:
          name: Telegram-unsigned
          path: build/outputs/Telegram-unsigned.ipa
